### ISSUE TITLE
Fails when a file uses the PackageImports extension

### ISSUE THREAD

**Issue by ilyakooo0** [mpickering/ghcide#40]
_originally posted: https://github.com/digital-asset/ghcide/issues/569_

I am fairly certain that the following error is related to the use of the PackageImports extension in the currently open file.

```
ghcide: very bad
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Import/FindImports.hs:78:23 in ghcide-0.1.0-B7KZ16czJifIz5r3YZOrKr:Development.IDE.Import.FindImports
```

**Comment by mpickering** [comment]
How do I reproduce this?

**Comment by ilyakooo0** [comment]
It seems to be reproducible by opening the following file in a project:

```haskell
{-# LANGUAGE PackageImports #-}

module Foo
  (
  ) where

import "aeson" Data.Aeson
```

**Comment by mpickering** [comment]
@ilyakooo0 Can you try building from master again? I added a slightly better diagnostic which may help us see what's going on.

**Comment by ilyakooo0** [comment]
By `master` you mean `hls`, right?

**Comment by mpickering** [comment]
Yes, sorry about that confusion.

**Comment by ilyakooo0** [comment]
```
ghcide: mkImportDirs: main
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Import/FindImports.hs:86:23 in ghcide-0.1.0-1cZQndkFIIrCG5hVUVKcRi:Development.IDE.Import.FindImports
```

**Comment by mpickering** [comment]
Thanks, that's very useful. Hopefully will get around to fixing it this week. It is probably safe to not error in this case if you want to make progress.

**Comment by mpickering** [comment]
Can you try this patch?

https://github.com/mpickering/ghcide/pull/45

**Comment by ilyakooo0** [comment]
I can confirm that the issue is not present in the `wip/refine-package-imports` branch.
