### ISSUE TITLE
Improve ghc session error handling

### ISSUE THREAD

**Issue by jneira** [mpickering/ghcide#8]
* If cradle run is succesful but ghc session crashes the ide does not get any error and progress gets stuck
* The workaround is extract compiler args and call ghc directly on command line to see what is going on
* Detected when opening ghc with hls on windows but i think the behaviour is similar with other projects

**Comment by mpickering** [comment]
@jneira The way to fix this is the make `optsGhcSession` return `Either [Diagnostic] HscEnvEq` and then `exe/Main` can report a proper diagnostic on failure.

**Comment by mpickering** [comment]
I have a patch for this now.

**Comment by mpickering** [comment]
This hie-bios issue would make it better - https://github.com/mpickering/hie-bios/issues/185

**Comment by jneira** [comment]
@mpickering i am afraid that the original issue finally was not fixed by #32. It handles errors running the cradle but the behaviour described was due to a failed ghc session caused by bad ghc args returned by a succesful cradle

I'll reopen it if you dont mind

**Comment by mpickering** [comment]
Sure, I didn't mean to close this issue.

**Comment by jneira** [comment]
It seems in linux the ghc init session error is being shown in the output (see https://github.com/haskell/haskell-language-server/issues/121#issuecomment-633304789) so the situation is slightly better than on windows
